routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'RecipeController@normal');

Route::get('/recipes', 'RecipeController@normal');

Auth::routes();
Route::middleware('auth')->group(function (){
    Route::get('admin/recipes', 'AdminController@recipes');
    Route::get('admin/ingredients', 'AdminController@ingredients');
    Route::get('admin/categories', 'AdminController@categories');
    Route::resources([
        'admin/recipes' => 'RecipeController',
        'admin/ingredients' => 'IngredientController',
        'admin/Categories' => 'CategoryController',
    ]);
});
Route::get('/home', 'HomeController@index')->name('home');

app/Recipe.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Recipe extends Model
{
    //
    // public function ingredients(){
    //     return $this->belongsToMany('Ingredient');
    // }   

    public function ingredients()
    {
        return $this->belongsToMany(Ingredient::class, 'recipe_ingredient');
    }
        public function category(){
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/RecipeController.php
<?php

namespace App\Http\Controllers;

use App\Recipe;
use App\Ingredient;
use DB;
use Illuminate\Http\Request;

class RecipeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        // $recipes = DB::table('recipes')->get();
        $recipes = Recipe::with('ingredients')->get();
        // return $recipes;
        // return $recipes;
        return view('admin.recipes', ['recipes' => $recipes, 'mode' => 'edit']);

    }
    public function normal()
    {
        // $recipes = DB::table('recipes')->get();
        $recipes = Recipe::with('ingredients')->get();
        return view('recipes.index', ['recipes' => $recipes, 'mode' => 'normal']);
    }

    public function search()
    {
        $q = "whatever";
        $user = User::where('name', 'LIKE', '%' . $q . '%')->orWhere('email', 'LIKE', '%' . $q . '%')->get();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $ingredients = Ingredient::all();
        return view('recipes.create', ['ingredients' => $ingredients]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $recipe = new Recipe();
        $recipe->name = $request->input('name');
        $recipe->description = $request->input('description');
        $recipe->save();

        $ingredients = Ingredient::find($request->input('ingredients'));
        $recipe->ingredients()->attach($ingredients);
        return redirect('admin/recipes');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Recipe  $recipe
     * @return \Illuminate\Http\Response
     */
    public function show(Recipe $recipe)
    {
        //
        return view('recipes.show', compact('recipes'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Recipe  $recipe
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $recipe = Recipe::find($id);
        return view('recipes.edit', ['recipe' => $recipe]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Recipe  $recipe
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $inputs = $request->except('_token', '_method');
        $recipe = Recipe::find($id);
        foreach ($inputs as $key => $value) {
            $recipe->$key = $value;
        }
        $recipe->save();
        return redirect('admin/recipes');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Recipe  $recipe
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $recipe = Recipe::find($id);
        $recipe->delete();
        return redirect('admin/recipes');
    }
    // public function ingredient()
    // {
    //     $ingredients = User::first()->ingredients(); 
    //     foreach ($ingredients as $ingredient) {
    //         echo $ingredient->name;
    //     }

    // }

}

resources/views/recipes/create.blade.php
@extends('admin.template')

@section('title', 'Créer Recettes')

@section('content')

<form class="ml-3 mr-3" method="POST" action="{{route('recipes.store')}}">
  @csrf
  <div class="form-group">
    <label for="name">name</label>
    <textarea type="name" name="name" class="form-control" id="name"></textarea>
  </div>
  <div class="form-group">
    <label for="description">description</label>
    <textarea type="description" name="description" class="form-control" id="description"></textarea>
  </div>
  <div class="form-group">
    <label for="exampleFormControlSelect2">Example multiple select</label>
    <select multiple class="form-control" id="exampleFormControlSelect2" name="ingredients[]">
      @foreach($ingredients as $ingredient)
      <option value={{$ingredient->id}}>{{$ingredient->name}}</option>

      @endforeach
    </select>
  </div>
  <button type="submit" class="btn btn-primary" style="margin-left:50%;">créer</button>
  @endsection

resources/views/recipes/edit.blade.php
@extends('admin.template')

@section('title', 'Modifier - Recettes')

@section('content')
<form class="ml-3 mr-3" method="POST" action="{{route('recipes.update', ['recipe' => $recipe->id])}}">
@method('PUT')
@csrf
<div class="row">
<div class="form-group">
    <label for="name">name</label>
    <textarea type="name" name="name" class="form-control" id="name">{{$recipe->name}}</textarea>
  </div>
  <div class="form-group">
    <label for="description">description</label>
    <textarea type="description" name="description" class="form-control" id="description">{{$recipe->description}}</textarea>
  </div>
</div>
{{-- <div class="form-group">
  <label for="exampleFormControlSelect1">Ingredient</label>
  <select class="form-control" name="ingredient">
    <option>{{$recipe->ingredient}}</option>

  </select>
</div> --}}
  <button type="submit" class="btn btn-primary" style="margin-left:50%;">Mettre à jour</button>
</form>
@endsection

resources/views/recipes/index.blade.php
@extends('layouts.template')
@section('title', 'Mes Recettes')
@section('content')
@component('components.recipes', ['recipes' => $recipes, 'mode' => 'normal'])
@endcomponent
@endsection